add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[directory]
style = "bold cyan"
truncation_length = 3
fish_style_pwd_dir_length = 1

[nodejs]
format = "via [󰎙 $version](bold green) "

[git_branch]
symbol = " "
style = "bold purple"