general {
    lock_cmd = hyprctl switchxkblayout at-translated-set-2-keyboard 0; pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session 
    after_sleep_cmd = hyprctl dispatch dpms on && powerprofilesctl set balanced
}

listener {
    timeout = 300
    on-timeout = hyprctl dispatch dpms off && powerprofilesctl set power-saver
    on-resume = hyprctl dispatch dpms on && powerprofilesctl set balanced
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

listener {
    timeout = 900
    on-timeout = ~/.config/scripts/suspend.sh
    on-resume = pkill -f suspend.sh
}