source = ~/.cache/wal/colors-hyprland.conf

animations {
    enabled = true
    
    bezier = linear, 1, 1, 0, 0
    bezier = easeOutQuint, 0.23, 1, 0.32, 1

    animation = fadeIn, 1, 2, linear
    animation = fadeOut, 1, 2, easeOutQuint

    animation = inputFieldDots, 1, 2, easeOutQuint
    animation = inputFieldColors, 1, 2, easeOutQuint
} 

background {
    monitor =
    path = /home/afterall/.cache/wallpaper
    color = $background
    blur_passes = 2
    blur_size = 4
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"
    color = $foreground
    font_size = 500
    font_family = Ubuntu
    halign = center
    valign = top
    position = 0, -400
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%A, %d %B")"
    color = $foreground
    font_size = 100
    font_family = Ubuntu
    halign = center
    valign = top
    position = 0, -1100
}

input-field {
    monitor =
    size = 1000, 100
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    
    inner_color = $background
    outer_color = $foreground
    check_color = $color2
    fail_color = $color3
    font_color = $foreground
    fade_on_empty = false
    font_family = Ubuntu
    placeholder_text = Enter password...
    fail_text = Try again...
    fail_timeout = 300
    
    halign = center
    valign = bottom
    position = 0, 400
}
