monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output.*HDMI*"
      },
      {
        node.name = "~alsa_input.*__Mic2__*"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]